OCIS_ROOT=${OCIS_ROOT:-"$HOME""/go/src/github.com/owncloud/ocis"}

export GRAPH_IDENTITY_BACKEND="ldap"
export GRAPH_LDAP_SERVER_WRITE_ENABLED="true"
export LDAP_URI="ldaps://localhost:9235"
export LDAP_INSECURE="true"
export LDAP_BIND_DN="uid=libregraph,ou=sysusers,o=libregraph-idm"
export LDAP_BIND_PASSWORD="idm"
export LDAP_USER_BASE_DN="ou=users,o=libregraph-idm"
export LDAP_USER_SCHEMA_ID="ownclouduuid"
export LDAP_USER_SCHEMA_MAIL="mail"
export LDAP_USER_SCHEMA_USERNAME="uid"
export LDAP_USER_OBJECTCLASS="inetOrgPerson"
export LDAP_GROUP_BASE_DN="ou=groups,o=libregraph-idm"
export LDAP_GROUP_SCHEMA_ID="ownclouduuid"
export LDAP_GROUP_SCHEMA_MAIL="mail"
export LDAP_GROUP_SCHEMA_GROUPNAME="cn"
export LDAP_GROUP_OBJECTCLASS="groupOfNames"
export IDP_INSECURE="true"
export IDP_LDAP_BIND_DN="uid=idp,ou=sysusers,o=libregraph-idm"
export IDP_LDAP_BIND_PASSWORD="idp"
export IDP_LDAP_BASE_DN="ou=users,o=libregraph-idm"
export IDP_LDAP_LOGIN_ATTRIBUTE="uid"
export PROXY_ACCOUNT_BACKEND_TYPE="cs3"
export PROXY_ENABLE_BASIC_AUTH="true"
export STORAGE_LDAP_BIND_DN="uid=reva,ou=sysusers,o=libregraph-idm"
export STORAGE_LDAP_BIND_PASSWORD="reva"
export OCS_ACCOUNT_BACKEND_TYPE="cs3"
export OCIS_RUN_EXTENSIONS="settings,storage-metadata,graph,graph-explorer,ocs,store,thumbnails,web,webdav,storage-frontend,storage-gateway,storage-userprovider,storage-groupprovider,storage-authbasic,storage-authbearer,storage-authmachine,storage-users,storage-shares,storage-public-link,storage-appprovider,storage-sharing,proxy,idp,nats,idm"
export OCIS_LOG_LEVEL="debug"
export OCIS_INSECURE="true"

"$OCIS_ROOT""/ocis/bin/ocis" server
